#!/usr/bin/env bash
#Configure the domain zone so that the subdomain www points to your load-balancer IP (lb-01)
query_subdomain () {
    local domain="$1"
    local subdomain="$2"
    local line
    line=$(dig "${subdomain}.${domain}" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "${subdomain} $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 2 ]
then
  query_subdomain "$1" "$2"
elif [ "$#" == 1 ]
then
  query_subdomain"$1" "www"
  query_subdomain "$1" "lb-01"
  query_subdomain "$1" "web-01"
  query_subdomain "$1" "web-02"
fi
