#!/usr/bin/env bash
#Script that configures a new Ubuntu machine
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo touch /var/www/html/index.html
sudo bash -c "hello world!" > /var/www/html/index.html
sudo service nginx restart
