#!/usr/bin/env bash
#Script that configures Nginx server so
#that /redirect_me is redirecting to another page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo touch /var/www/html/index.html
sudo echo  "Hello World!" | sudo tee /var/www/html/index.html
cat << 'EOF' | sudo tee /etc/nginx/sites-available/default
server {
    listen 80;
    listen [::]:80;

    root /var/www/html;
    index index.html;

    server_name_;
    # Redirect /redirect_me to another page
    location = /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    location / {
        try_files $uri $uri/ =404;
    }
}
EOF
sudo service nginx restart
