#!/usr/bin/env bash
#Script that configures Nginx server so
#that /redirect_me is redirecting to another page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo touch /var/www/html/index.html
sudo echo  "Hello World!" | sudo tee /var/www/html/index.html
cat << 'EOF' | sudo tee /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;
    error_page 404 /404.html;
    location = /404.html {
        internal;
        default_type text/html;
        return 404 "Ceci n'est pas une page";
    }
}
EOF
sudo service nginx restart