#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.
sudo apt update -y
sudo apt install haproxy -y
cat << 'EOF' | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    option  httplog
    option  dontlognull
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms

frontend http_front
    bind *:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server 531208-web-01 54.236.45.210:80 check
    server 531208-web-02 54.197.82.208:80 check
EOF